# Generated by Django 5.1.5 on 2025-02-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_product_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='add',
            new_name='add_left',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='cyl',
            new_name='add_right',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='axis',
            new_name='axis_left',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='sph',
            new_name='cyl_left',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='vision',
            new_name='vision_left',
        ),
        migrations.AddField(
            model_name='customer',
            name='axis_right',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cyl_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sph_left',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sph_right',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='vision_right',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
