# Generated by Django 5.1.5 on 2025-02-04 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_add_customer_add_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_booking',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_purchase',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='frame_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='frame_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='frame_type',
            field=models.CharField(blank=True, choices=[('MT', 'Metal'), ('PL', 'Plastic'), ('OT', 'Other')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lens_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lens_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='lens_type',
            field=models.CharField(blank=True, choices=[('SV', 'Single Vision'), ('BF', 'Bifocal'), ('PR', 'Progressive')], max_length=2, null=True),
        ),
    ]
