# Generated by Django 5.1.5 on 2025-02-08 06:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customerhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sph_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sph_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cyl_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cyl_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('axis_left', models.IntegerField(blank=True, null=True)),
                ('axis_right', models.IntegerField(blank=True, null=True)),
                ('add_left', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('add_right', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vision_left', models.CharField(blank=True, max_length=255, null=True)),
                ('vision_right', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lens_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lens_type', models.CharField(blank=True, choices=[('SV', 'Single Vision'), ('BF', 'Bifocal'), ('PR', 'Progressive')], max_length=2, null=True)),
                ('lens_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('frame_name', models.CharField(blank=True, max_length=255, null=True)),
                ('frame_type', models.CharField(blank=True, choices=[('MT', 'Metal'), ('PL', 'Plastic'), ('OT', 'Other')], max_length=2, null=True)),
                ('frame_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_of_purchase', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='customers.customer')),
            ],
        ),
    ]
