# Generated by Django 5.1.5 on 2025-02-10 17:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_bill_delete_inventoryitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('user', 'phone')},
        ),
    ]
