# Generated by Django 5.1.5 on 2025-02-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lens_index',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lens index value (e.g., 1.50, 1.60, etc.)', max_digits=5, null=True),
        ),
    ]
