# Generated by Django 5.1.5 on 2025-02-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_customer_lens_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='frame_cost',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='frame_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='frame_type',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='lens_cost',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='lens_name',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='lens_type',
        ),
        migrations.AddField(
            model_name='purchase',
            name='details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
