# Generated by Django 5.1.5 on 2025-03-27 08:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_remove_purchase_frame_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-prescription_date']},
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='unique_customer_phone_per_user',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('user', 'phone')},
        ),
        migrations.AddField(
            model_name='customer',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='prescription_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_booking',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_purchase',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='frame_cost',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='frame_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='frame_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lens_cost',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lens_index',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lens_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lens_type',
        ),
    ]
